import type {
  InfoPlace,
  ProfileInfo,
  ReelInfo,
  SavedPlaceInfo,
} from './types';

export const frontendInfoDomainMock: {
  profiles: ProfileInfo[];
  places: InfoPlace[];
  reels: ReelInfo[];
  savedPlaces: SavedPlaceInfo[];
} = {
  profiles: [
    {
      id: 'profile-yeogidam-user',
      nickname: '여기담 사용자',
      description: '릴스로 발견한 장소를 차곡차곡 저장하고 있어요.',
      avatarUrl: 'https://images.example.com/profiles/yeogidam-user.png',
      createdAt: '2026-08-01T09:00:00+09:00',
      updatedAt: '2026-08-13T09:30:00+09:00',
    },
  ],
  places: [
    {
      id: 'cafe-onwol',
      kakaoPlaceId: '26338954',
      googlePlaceId: 'ChIJi7YeogidamCafeOnwol',
      name: '카카오프렌즈 코엑스점',
      category: '가정,생활 > 문구',
      roadAddress: '서울 강남구 영동대로 513',
      address: '서울 강남구 삼성동 159',
      latitude: 37.51207412593136,
      longitude: 127.05902969025047,
      kakaoPlaceUrl: 'http://place.map.kakao.com/26338954',
      telephone: '02-6002-1880',
      thumbnailUrl: 'https://images.example.com/places/cafe-onwol.jpg',
      thumbnailSource: 'kakao',
      photoAttribution: 'Kakao Place',
      sourceAddress: '서울 강남구 삼성동 159',
      createdAt: '2026-08-03T11:00:00+09:00',
    },
    {
      id: 'monoroom',
      kakaoPlaceId: '28190211',
      googlePlaceId: 'ChIJyeogidamMonoroom',
      name: '모노룸 커피',
      category: '음식점 > 카페',
      roadAddress: '서울 마포구 동교로24길 12 1층',
      address: '서울 마포구 연남동 566-12',
      latitude: 37.5574,
      longitude: 126.9254,
      kakaoPlaceUrl: 'http://place.map.kakao.com/28190211',
      telephone: '070-4123-0001',
      thumbnailUrl: 'https://images.example.com/places/monoroom.jpg',
      thumbnailSource: 'instagram',
      photoAttribution: '@seoul_sources',
      sourceAddress: '서울 마포구 동교로24길 12',
      createdAt: '2026-08-05T13:30:00+09:00',
    },
  ],
  reels: [
    {
      id: 'reel-cafe-onwol-1',
      userId: 'profile-yeogidam-user',
      placeId: 'cafe-onwol',
      instagramUrl: 'https://www.instagram.com/reel/CafeOnwol123/',
      instagramAuthorUsername: 'seoul_sources',
      instagramTitle: '서울 한복판에서 만나는 감각적인 공간',
      instagramDescription: '주말에 들르기 좋은 서울 공간 기록.',
      instagramThumbnailUrl: 'https://images.example.com/reels/cafe-onwol.jpg',
      source: 'instagram_share',
      processingStatus: 'COMPLETED',
      failureReason: null,
      instagramShortcode: 'CafeOnwol123',
      processingVersion: 1,
      createdAt: '2026-08-09T18:20:00+09:00',
      updatedAt: '2026-08-09T18:21:30+09:00',
    },
    {
      id: 'reel-monoroom-1',
      userId: 'profile-yeogidam-user',
      placeId: 'monoroom',
      instagramUrl: 'https://www.instagram.com/reel/Monoroom456/',
      instagramAuthorUsername: null,
      instagramTitle: '연남동 골목에서 발견한 모노톤 카페',
      instagramDescription: '저장해두고 다시 방문하고 싶은 공간.',
      instagramThumbnailUrl: 'https://images.example.com/reels/monoroom.jpg',
      source: 'url_input',
      processingStatus: 'COMPLETED',
      failureReason: null,
      instagramShortcode: 'Monoroom456',
      processingVersion: 2,
      createdAt: '2026-08-11T10:05:00+09:00',
      updatedAt: '2026-08-11T10:06:10+09:00',
    },
  ],
  savedPlaces: [
    {
      id: 'saved-place-1',
      userId: 'profile-yeogidam-user',
      placeId: 'cafe-onwol',
      thumbnailUrl: 'https://images.example.com/places/cafe-onwol.jpg',
      createdAt: '2026-08-09T18:25:00+09:00',
    },
    {
      id: 'saved-place-2',
      userId: 'profile-yeogidam-user',
      placeId: 'monoroom',
      thumbnailUrl: 'https://images.example.com/places/monoroom.jpg',
      createdAt: '2026-08-11T10:07:00+09:00',
    },
  ],
};
