import type { FrontendInfoDomain } from './types';

export const frontendInfoDomainMock: FrontendInfoDomain = {
  profiles: [
    {
      id: 'profile-yeogidam-user',
      nickname: '여기담 사용자',
      description: '릴스로 발견한 장소를 차곡차곡 저장하고 있어요.',
      avatarUrl: 'https://images.example.com/profiles/yeogidam-user.png',
      createdAt: '2026-08-01T09:00:00+09:00',
      updatedAt: '2026-08-13T09:30:00+09:00',
    },
    {
      id: 'profile-seoul-sources',
      nickname: '서울 소스',
      description: '서울의 감도 높은 공간을 소개합니다.',
      avatarUrl: 'https://images.example.com/profiles/seoul-sources.png',
      createdAt: '2026-07-18T14:20:00+09:00',
      updatedAt: '2026-08-10T08:15:00+09:00',
    },
  ],
  places: [
    {
      id: 'cafe-onwol',
      kakaoPlaceId: '26338954',
      googlePlaceId: 'ChIJi7YeogidamCafeOnwol',
      name: '카카오프렌즈 코엑스점',
      category: '가정,생활 > 문구',
      roadAddress: '서울 강남구 영동대로 513',
      address: '서울 강남구 삼성동 159',
      latitude: 37.51207412593136,
      longitude: 127.05902969025047,
      kakaoPlaceUrl: 'http://place.map.kakao.com/26338954',
      telephone: '02-6002-1880',
      thumbnailUrl: 'https://images.example.com/places/cafe-onwol.jpg',
      thumbnailSource: 'kakao',
      photoAttribution: 'Kakao Place',
      sourceAddress: '서울 강남구 삼성동 159',
      createdAt: '2026-08-03T11:00:00+09:00',
    },
    {
      id: 'monoroom',
      kakaoPlaceId: '28190211',
      googlePlaceId: 'ChIJyeogidamMonoroom',
      name: '모노룸 커피',
      category: '음식점 > 카페',
      roadAddress: '서울 마포구 동교로24길 12 1층',
      address: '서울 마포구 연남동 566-12',
      latitude: 37.5574,
      longitude: 126.9254,
      kakaoPlaceUrl: 'http://place.map.kakao.com/28190211',
      telephone: '070-4123-0001',
      thumbnailUrl: 'https://images.example.com/places/monoroom.jpg',
      thumbnailSource: 'instagram',
      photoAttribution: '@seoul_sources',
      sourceAddress: '서울 마포구 동교로24길 12',
      createdAt: '2026-08-05T13:30:00+09:00',
    },
    {
      id: 'layer',
      kakaoPlaceId: '32099877',
      name: '레이어 커피바',
      category: '음식점 > 카페',
      roadAddress: '서울 강남구 도산대로45길 18',
      address: '서울 강남구 신사동 654-21',
      latitude: 37.5239,
      longitude: 127.0388,
      kakaoPlaceUrl: 'http://place.map.kakao.com/32099877',
      telephone: null,
      thumbnailUrl: 'https://images.example.com/places/layer.jpg',
      thumbnailSource: 'manual',
      photoAttribution: null,
      sourceAddress: '서울 강남구 도산대로45길 18',
      createdAt: '2026-08-07T16:40:00+09:00',
    },
  ],
  reels: [
    {
      id: 'reel-cafe-onwol-1',
      userId: 'profile-seoul-sources',
      placeId: 'cafe-onwol',
      instagramUrl: 'https://www.instagram.com/reel/CafeOnwol123/',
      instagramAuthorUsername: 'seoul_sources',
      instagramTitle: '서울 한복판에서 만나는 감각적인 공간',
      instagramDescription: '주말에 들르기 좋은 서울 공간 기록.',
      instagramThumbnailUrl: 'https://images.example.com/reels/cafe-onwol.jpg',
      source: 'instagram_share',
      processingStatus: 'COMPLETED',
      failureReason: null,
      instagramShortcode: 'CafeOnwol123',
      processingVersion: 1,
      createdAt: '2026-08-09T18:20:00+09:00',
      updatedAt: '2026-08-09T18:21:30+09:00',
    },
    {
      id: 'reel-monoroom-1',
      userId: 'profile-yeogidam-user',
      placeId: 'monoroom',
      instagramUrl: 'https://www.instagram.com/reel/Monoroom456/',
      instagramAuthorUsername: null,
      instagramTitle: '연남동 골목에서 발견한 모노톤 카페',
      instagramDescription: '저장해두고 다시 방문하고 싶은 공간.',
      instagramThumbnailUrl: 'https://images.example.com/reels/monoroom.jpg',
      source: 'url_input',
      processingStatus: 'COMPLETED',
      failureReason: null,
      instagramShortcode: 'Monoroom456',
      processingVersion: 2,
      createdAt: '2026-08-11T10:05:00+09:00',
      updatedAt: '2026-08-11T10:06:10+09:00',
    },
    {
      id: 'reel-layer-1',
      userId: 'profile-yeogidam-user',
      placeId: null,
      instagramUrl: 'https://www.instagram.com/reel/Layer789/',
      instagramAuthorUsername: null,
      instagramTitle: '압구정 감성 공간 스냅',
      instagramDescription: null,
      instagramThumbnailUrl: 'https://images.example.com/reels/layer.jpg',
      source: 'instagram_share',
      processingStatus: 'FAILED',
      failureReason: 'PLACE_NOT_FOUND',
      instagramShortcode: 'Layer789',
      processingVersion: 1,
      createdAt: '2026-08-12T20:12:00+09:00',
      updatedAt: '2026-08-12T20:14:48+09:00',
    },
  ],
  savedPlaces: [
    {
      id: 'saved-place-1',
      userId: 'profile-yeogidam-user',
      placeId: 'cafe-onwol',
      thumbnailUrl: 'https://images.example.com/places/cafe-onwol.jpg',
      createdAt: '2026-08-09T18:25:00+09:00',
    },
    {
      id: 'saved-place-2',
      userId: 'profile-yeogidam-user',
      placeId: 'monoroom',
      thumbnailUrl: 'https://images.example.com/places/monoroom.jpg',
      createdAt: '2026-08-11T10:07:00+09:00',
    },
  ],
  providerUsageMonthly: [
    {
      provider: 'instagram',
      monthStart: '2026-08-01',
      requestCount: 14,
      updatedAt: '2026-08-13T08:00:00+09:00',
    },
    {
      provider: 'kakao-map',
      monthStart: '2026-08-01',
      requestCount: 8,
      updatedAt: '2026-08-13T08:10:00+09:00',
    },
  ],
  reelPlaces: [
    {
      reelId: 'reel-cafe-onwol-1',
      placeId: 'cafe-onwol',
      position: 0,
      createdAt: '2026-08-09T18:21:00+09:00',
    },
    {
      reelId: 'reel-monoroom-1',
      placeId: 'monoroom',
      position: 0,
      createdAt: '2026-08-11T10:06:00+09:00',
    },
  ],
  reelPlaceMatchFailures: [
    {
      reelId: 'reel-layer-1',
      guessIndex: 0,
      placeName: '레이어 커피바',
      sourceAddress: '서울 압구정 인근',
      sourceRegion: '서울 강남구',
      failureStage: 'FINAL_GUARD',
      failureReason: 'INSUFFICIENT_ADDRESS_EVIDENCE',
      searchOrigin: 'INITIAL',
      classifierReason: 'NO_VERIFIED_CANDIDATE',
      candidateCount: 2,
      candidateIds: ['32099877', '45312819'],
      createdAt: '2026-08-12T20:14:40+09:00',
    },
  ],
};
